### ISSUE TITLE
How to install on Kali Linux

### ISSUE THREAD

**Issue by sidrocks77** [stefan2200/Helios#1]
HI,
I used pip3 install Helios-Scanner which installed Helios but when I am providing helios command it says command not found.
Also I downloaded files using git clone but not able to install. Below error. How to install and execute this?

![image](https://user-images.githubusercontent.com/86314063/123846422-f9f35c80-d932-11eb-9016-198bfbd089d3.png)

**Comment by sidrocks77** [comment]
okay managed to install with sudo access. But now when I ran the command I got below error while finishing the scan. Any suggestions?
![image](https://user-images.githubusercontent.com/86314063/123850832-1cd43f80-d938-11eb-900d-f866050bb3d1.png)

**Comment by stefan2200** [comment]
Hello, it has been a while since I worked on this project but it looks like the installed module does not have the CVE databases available. `helios-update-db` or `sudo helios-update-db` should resolve the issue, not sure which one works on Kali.

Please let me know if that resolves it :)

**Comment by sidrocks77** [comment]
Hi,
Thanks for responding. The update did resolve that error but after writing to json output file the script is not quitting itself and i had to kill it. Any idea how this will auto complete without manual kill.
![image](https://user-images.githubusercontent.com/86314063/124167954-1f62a080-dac2-11eb-8a5e-f5a1f2e8a03d.png)

**Comment by sidrocks77** [comment]
i used this command:
helios -u http://192.168.0.106 -v --optimize -a --threads 1000 --options all --sslverify -o "/home/kali/Desktop/scan_reports/helios_scan.$(date +%Y-%m-%d_%H:%M).json"

**Comment by stefan2200** [comment]
I would suggest removing the `--optimize` argument and lowering the threads to something in the range of 10-20. Starting 1000 simultaneous threads will most likely cause memory issues resulting in the error you are experiencing.

**Comment by sidrocks77** [comment]
that worked perfectly. thanks again
